### ISSUE TITLE
Error 0161:null

### ISSUE THREAD

**Issue by Godrules500** [salcosta/vsc-servicenow-sync#10]
I am trying to sync files from our dev instance and I am receiving Error 0161:null

**Comment by salcosta** [comment]
Almost a year has passed with no update...gonna mark this closed. Please reopen if it is continuing to happen.

**Comment by RickSeiden** [comment]
I am having this happen as well. I did an inital sync of some script includes, and now when I try to sync anymore, I get this error.  I'm able to see if a file is up to date, and I'm able to update scripts that have already been synced.

Steps to reproduce:
1) right click in the folder, and select SN Sync: Sync Record
2) Receive error
3) Right click in the folder and select SN Sync: Sync Multiple Records
4) Paste in encoded query in prompt
5) Receive error
6) Control Shift P and select SN Sync: Sync Record
7) Receive different error: "Command 'SN Sync: Sync Record' resulted in an error (Running the contributed command: 'sn_sync.syncRecord' failed.)"

I am able to right click on the folder/table name (like sys_script_include) and select sync record or sync multiple, and it works.
