### ISSUE TITLE
Cannot synchronize files whose name contains slash 

### ISSUE THREAD

**Issue by kukuruznik** [salcosta/vsc-servicenow-sync#11]
Using the name field to generate local file names is convenient because one can find a file by name. But this field has no restrictions on its format and can contain the slash / backslash character, that is invalid in file names (depending on the operating system).

This bug does not only prevent such files from being synchronized but also any other files from the same directory (all files that are placed in the downloaded collection after the one with slashes are skipped).

**Comment by salcosta** [comment]
Not sure why you are putting slashes in your filenames but fixing it anyways!

**Comment by kukuruznik** [comment]
Some script includes on my customer's instance contained slashes in their names. They only became filenames after being synchronized to local file system via this plugin (before the fix). Now it works fine, thank you for your effort.
