### ISSUE TITLE
Error 0161:Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by johncaruso** [salcosta/vsc-servicenow-sync#13]
If using behind a corporate firewall, you may encounter the subject error when this extension attempts to make an http request to your instance.

A workaround is to install another extension: [win-ca](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca)

This extension makes Windows trusted root certificates available to VSCode extensions.

This resolved the self signed certificate issue for me. 

@salcosta There is an open vscode [issue](https://github.com/Microsoft/vscode/issues/52880) related to this, so hopefully they'll address this in vscode instead of depending on extension authors to deal with. But if you want to fix this sooner, I believe you can leverage the win-ca node package.

Also, while your doing your housekeeping, please consider pulling in PR #5 - definitely would like the ability to run background scripts within VS Code.

**Comment by salcosta** [comment]
Any idea if this is still an issue?

**Comment by johncaruso** [comment]
It's in their March milestone, so should be fixed soon.
