### ISSUE TITLE
Whole Extension doesn't work after update

### ISSUE THREAD

**Issue by neo29** [salcosta/vsc-servicenow-sync#14]
Hello,

after the last update I cannot sync anything with SNOW instance.
Also if I wanted to use command "Connect to ServiceNow" I got the error "command 'sn_sync.enterConnectionSettings' not found".

Could you have a look at this issue please?

BTW Nice extension ;-)

**Comment by salcosta** [comment]
Looking at it right now, thanks!  Stay tuned to SNDevs for an update.

**Comment by salcosta** [comment]
Found it was due to a reference to a dev dependency being in the main file. Didn't catch it because the file existed on my system. Removed and tested against a clean system. Should be good in the 0.2.2 release.

Thanks!
