### ISSUE TITLE
I would love to get updated files via npm run script or cli call

### ISSUE THREAD

**Issue by jacebenson** [salcosta/vsc-servicenow-sync#9]
Any chance of splitting this into two repos one, to manage the files/creation/update via npm module, any then this to be a wrapper for this?

I'd start it but I'm not sure you as repo owner are even interested in this.

**Comment by mak42** [comment]
Hello jacebenson,

I started working on something similar, I want to create a NodeJS library with the following functionality:

- Sync Records from Service-Now to disk and also from disk to Service-Now e.g. it should be possible to create a new business rule.
- Evaluate Files/Scripts in Service-Now
- Make a GlideAjax Request
- Query Data
- Export Data
- Import Data via XML
- Get Current Update-Set
- Change Update-Set
- Get Current Application
- Change Application

And then write a cli-wrapper for this library, currently its more an idea then reality don't know how long it will actually take me for the first alpha version of the library. If you are interested it will go in this github repo: https://github.com/mak42/sncmder

**Comment by salcosta** [comment]
I have a separate library that did that, but I always end up just writing it from scratch each time.  I might consider it or contribute to an existing one.
